server:
  port: 8080

spring:
  profiles:
    active: dev

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS}

  admin:
    username: ${ADMIN_USERNAME}
    password: ${ADMIN_PASSWORD}
